import { Container } from "@/components/Common/Container";
import Hero from "@/components/Hero";
import Features from "@/components/Features";
import Benefits from "@/components/Benefits";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <Container className="max-w-c-1390">
      <Hero />
      <Features />
      <Benefits />
    </Container>
  );
}
